name: Pull Requests

on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  # Runs the linter
  PR:
    name: PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: web/trivia-ui/package-lock.json
      - run: make build-ui
      - name: vet
        run: go vet ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.43
      - name: Unit Tests
        run: |
          make test-ci
      - name: Annotate tests
        if: always()
        uses: guyarb/golang-test-annoations@v0.3.0
        with:
          test-results: unit-test.json
      - name: Build
        run: |
          make build-full
