name: Release

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: go-semantic-release/action@v1
        with:
          allow-initial-development-versions: true
          force-bump-patch-version: true